// <auto-generated />
using System;
using GameServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250320112026_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameServer.CollectionDb", b =>
                {
                    b.Property<int>("OwnerDbId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("ProgressFlag")
                        .HasColumnType("int");

                    b.HasKey("OwnerDbId", "TemplateId");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("GameServer.HeroDb", b =>
                {
                    b.Property<int>("HeroDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeroDbId"));

                    b.Property<long>("AccountDbId")
                        .HasColumnType("bigint");

                    b.Property<int>("ClassType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<int>("Mp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PosX")
                        .HasColumnType("int");

                    b.Property<int?>("PosY")
                        .HasColumnType("int");

                    b.HasKey("HeroDbId");

                    b.HasIndex("AccountDbId");

                    b.HasIndex("Name");

                    b.ToTable("Hero");
                });

            modelBuilder.Entity("GameServer.ItemDb", b =>
                {
                    b.Property<long>("ItemDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemDbId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("EquipSlot")
                        .HasColumnType("int");

                    b.Property<int>("OwnerDbId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("ItemDbId");

                    b.HasIndex("OwnerDbId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("GameServer.QuestDb", b =>
                {
                    b.Property<int>("OwnerDbId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("OwnerDbId", "TemplateId");

                    b.ToTable("Quest");
                });

            modelBuilder.Entity("GameServer.CollectionDb", b =>
                {
                    b.HasOne("GameServer.HeroDb", "OwnerDb")
                        .WithMany("Collections")
                        .HasForeignKey("OwnerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerDb");
                });

            modelBuilder.Entity("GameServer.ItemDb", b =>
                {
                    b.HasOne("GameServer.HeroDb", "OwnerDb")
                        .WithMany("Items")
                        .HasForeignKey("OwnerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerDb");
                });

            modelBuilder.Entity("GameServer.QuestDb", b =>
                {
                    b.HasOne("GameServer.HeroDb", "OwnerDb")
                        .WithMany("Quests")
                        .HasForeignKey("OwnerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("GameServer.QuestTaskDb", "QuestTasks", b1 =>
                        {
                            b1.Property<int>("QuestDbOwnerDbId")
                                .HasColumnType("int");

                            b1.Property<int>("QuestDbTemplateId")
                                .HasColumnType("int");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.PrimitiveCollection<string>("ObjectiveCounts")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.PrimitiveCollection<string>("ObjectiveTemplateIds")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("QuestDbOwnerDbId", "QuestDbTemplateId", "__synthesizedOrdinal");

                            b1.ToTable("Quest");

                            b1.ToJson("QuestTasks");

                            b1.WithOwner()
                                .HasForeignKey("QuestDbOwnerDbId", "QuestDbTemplateId");
                        });

                    b.Navigation("OwnerDb");

                    b.Navigation("QuestTasks");
                });

            modelBuilder.Entity("GameServer.HeroDb", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Items");

                    b.Navigation("Quests");
                });
#pragma warning restore 612, 618
        }
    }
}
